#!/bin/bash

# Obtenir le nom de la branche actuelle dans le dépôt Git
curr=$(git rev-parse --abbrev-ref HEAD)

# Vérifier si la variable $curr contient "HEAD"
if [ "$curr" = "HEAD" ]; then
    # Si c'est "HEAD", cela signifie que l'utilisateur n'est pas sur une branche
    echo "Vous n'êtes pas sur une branche." >&2
else
    # Sinon, afficher le nom de la branche actuelle
    echo "Branche actuelle : $curr"
fi
